name: cross_point
description: Cross point demo

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  #Service
  dio:  ^4.0.6
  path_provider: ^2.0.11

  #Locale Manager
  hive_flutter: ^1.1.0
  hive: ^2.2.3

  #Basic Design Pattern Helper
  get_it: ^7.2.0

  #state managment
  flutter_riverpod: ^1.0.3
  state_notifier: ^0.7.2+1

  #Sliding_bottom
  sliding_up_panel: ^2.0.0+1

  #Mobx
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  mobx_codegen: ^2.0.5+2



  #firebase_dynamic_links:



  # JSON
  json_serializable: ^6.1.3
  json_annotation: ^4.4.0


  #Responsive
  sizer: ^2.0.15

  #animations
  lottie: ^1.2.1
  dots_indicator: ^2.0.0
  fluttertoast: ^8.0.8

  #images
  flutter_svg: ^1.0.3
  image_pixels: ^3.0.0

  #time
  ntp: ^2.0.0

  #date format
  intl: ^0.17.0


  #adaptive_dialog:
  adaptive_dialog: ^1.8.0+1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Black.ttf
        - asset: assets/font/Poppins-BlackItalic.ttf
        - asset: assets/font/Poppins-Bold.ttf
        - asset: assets/font/Poppins-BoldItalic.ttf
        - asset: assets/font/Poppins-ExtraBold.ttf
        - asset: assets/font/Poppins-ExtraBoldItalic.ttf
        - asset: assets/font/Poppins-ExtraLight.ttf
        - asset: assets/font/Poppins-ExtraLightItalic.ttf
        - asset: assets/font/Poppins-Italic.ttf
        - asset: assets/font/Poppins-LightItalic.ttf
        - asset: assets/font/Poppins-Medium.ttf
        - asset: assets/font/Poppins-MediumItalic.ttf
        - asset: assets/font/Poppins-Regular.ttf
        - asset: assets/font/Poppins-SemiBold.ttf
        - asset: assets/font/Poppins-SemiBoldItalic.ttf
        - asset: assets/font/Poppins-Thin.ttf
        - asset: assets/font/Poppins-ThinItalic.ttf

