name: audiotodo
description: This app convert your audio files to todo!

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter

  intl: ^0.17.0



  #neumorphic:
  flutter_neumorphic: ^3.2.0

  json_serializable: ^6.6.1
  freezed_annotation: ^2.2.0


  flutter_downloader: ^1.10.2
  file_picker: ^5.2.9

  awesome_dialog: ^3.0.2
  avatar_glow: ^2.0.2


  #firebase_database
  firebase_storage: ^11.0.6
  cloud_firestore: ^4.1.0
  firebase_auth: ^4.1.5
  firebase_core: ^2.10.0

  #db_help
  uuid: ^3.0.7

  path_provider: ^2.0.14
  get_it: ^7.2.0

  flutter_localization: ^0.1.10
  #ui_helpers
  responsive_sizer: ^3.1.1
  animated_notch_bottom_bar: ^0.0.6
  animated_text_kit: ^4.2.2

  permission_handler: ^10.2.0
  flutter_riverpod: ^2.3.5

  cupertino_icons: ^1.0.2

  #chat gpt
  chat_gpt_sdk: ^2.1.2

  #SPEECH TO TEXT
  speech_to_text: ^6.1.1
  audio_waveforms: ^1.0.4

  logger: ^1.3.0
  intl_utils: ^2.8.2
  dio: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  freezed: ^2.2.1
  json_serializable: ^6.5.4

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-BlackItalic.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-LightItalic.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-MediumItalic.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
        - asset: assets/fonts/Poppins-Thin.ttf

flutter_intl:
  enabled: true




