name: osgb
description: osgb

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Localizations
  ntp: ^2.0.0
  intl: ^0.17.0


  #cached_network_image:
  cached_network_image: ^3.2.3


  #tabbar:
  tab_container: ^2.0.0
  flutter_advanced_drawer: ^1.3.2

  #qr_flutter:
  qr_flutter: ^4.0.0

  #date
  date_time_picker: ^2.1.0

  #images:
  image_picker: ^0.8.6
  image_cropper: ^3.0.1
  file_picker: ^5.2.4
  open_filex: ^4.3.2
  #path
  path_provider: ^2.0.11
  android_path_provider: ^0.3.0

  #state managment
  flutter_riverpod: ^2.1.1
  state_notifier: ^0.7.2+1

  #Model Works
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4

  #Toast Messages...
  fluttertoast: ^8.1.1

  #ui_helpers
  responsive_sizer: ^3.1.1
  search_choices: ^2.2.1





  #Firebase Database
  firebase_auth: ^4.1.5
  firebase_core: ^2.3.0
  firebase_storage: ^11.0.6
  cloud_firestore: ^4.1.0

  #appBadger
  flutter_app_badger: ^1.5.0

  #Push Notification
  flutter_local_notifications: ^12.0.4
  firebase_messaging: ^14.1.3
  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  nanoid: ^1.0.0
  flutter_barcode_scanner: ^2.0.0
  dots_indicator: ^2.1.0
  photo_view: ^0.14.0
  search_page: ^2.2.0
  gallery_saver: ^2.3.2
  dio: ^4.0.6
  image_gallery_saver: ^1.7.1
  url_launcher: ^6.1.7

  pdf_viewer_plugin: ^2.0.1
  pdf: any
  share_plus: ^6.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.2


flutter:

  uses-material-design: true

  assets:

    - assets/image/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-BlackItalic.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-LightItalic.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-MediumItalic.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-ThinItalic.ttf

